### ISSUE TITLE
Set up restore points for S3 in AWS

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1818]
**Backup on the S3 needs to be set up**
H5P library files, and other uploaded files are not part of the backup that runs every night.

**Suggested solution**
A daily backup for the S3 in addition to the existing backup. This should probably not to long after the other backup has started.

**Comment by tmkarlsen** [comment]
NOTE: first we need to verify that this isn't covered by the general backup.

**Comment by Kamelon7** [comment]
S3 buckets are replicated to the Backup AWS account. All Edlib accounts has the same setup, so all the S3 buckets related to Edlib are being backed up already.
![Edlib S3 backups](https://user-images.githubusercontent.com/82902462/206657601-d36fea8a-d597-474b-953b-9193f03aad81.png)

**Comment by emmachughes** [comment]
@Kamelon7 it wasn't mentioned here, but we already knew S3 backups technically do exist. The issue is they're set up as simple bucket replication. This is probably fine for recovering from a catastrophe, but if all need to do is roll back a night or two, then this isn't fit for purpose. At least I'd have no idea how to roll back to a specific point. 🙃

The RDS backups are set up as recovery points in AWS Backup. We need S3 backups to be set up this way, too. I'll reopen the issue and give it a more appropriate title.

**Comment by Kamelon7** [comment]
Build was broken but only needs minor modifications. The issue has been moved to internal reporting system.
