### ISSUE TITLE
Bulk update error messages (prod and test)

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2652]
**Bulk update fails for drag and drop**
When trying to bulk update H5P.DragQuestion 1.13.15, all content fails with on of the two error messages below

Request URL: 
https://ca.h5p-test.ndla.no/content/upgrade/library?library=/H5P.DragQuestion/1/14

**Error messages**
An error occurred while processing parameters:
Cannot read properties of undefined (reading 'task')

An error occurred while processing parameters:
dropzone.correctElements.filter is not a function

**Screenshots**

![Skjermbilde 2024-01-04 kl  13 18 25](https://github.com/cerpus/Edlib/assets/38659798/a9a81618-d056-4184-ade6-61f178508d1b)

![Skjermbilde 2024-01-04 kl  12 24 44](https://github.com/cerpus/Edlib/assets/38659798/1e2366d4-29a4-4172-9b88-d56aee61534f)

**Comment by chrieinv** [comment]
Looks like you are upgrading to 1.14, but what patch version?

**Comment by tmkarlsen** [comment]
I'm trying to update to  1.14.15 
![Skjermbilde 2024-01-04 kl  13 18 25](https://github.com/cerpus/Edlib/assets/38659798/6cd0a487-71a8-4ce9-ab3a-8a0282981f45)

**Comment by chrieinv** [comment]
Looking at the upgrades script it seems like all errors are due to issues with the content.
- The ones with `reading 'task'` error don't have any questions defined
- The correct elements should be set as an array. The `dropzone.correctElements.filter is not a function` error occurs if it's not an array

These issues could be corrected in the upgrade script or a check could be added to prevent errors. In previous upgrades, like the one to 1.13, the code checks if 'questions' exists before trying to access it, this is not done in the 1.14 upgrade.
