### ISSUE TITLE
H5P tutorial and example is missing in CA

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#487]
**Missing H5P tutorial and example**
The tutorial and example that is supposed to be shown beneath the H5P client container are missing. Possibly due to different integration of the H5P hub and following missing href and style setting.

**To Reproduce**
Create or open any existing H5P.

**Screenshots**
<img width="956" alt="Skjermbilde 2022-01-31 kl  21 49 20" src="https://user-images.githubusercontent.com/38659798/151986601-63267887-76de-414f-8473-d932045ac0df.png">

![Skjermbilde 2022-02-01 kl  15 22 07](https://user-images.githubusercontent.com/38659798/151986676-d52e392c-b43c-4cd0-a3a9-7de6c440d409.png)

![Skjermbilde 2022-02-07 kl  09 28 06](https://user-images.githubusercontent.com/38659798/152757513-5bf863b1-af9b-4d60-8c23-ef78849b2dc3.png)

![Skjermbilde 2022-02-01 kl  15 29 21](https://user-images.githubusercontent.com/38659798/151987111-a4eab74d-b111-4235-a9eb-2459d18499ad.png)

**Comment by chrieinv** [comment]
This is because the hub is disabled when editing, not sure why this restriction is set. There is a `.env` setting that supposedly controls if the hub is enabled or not, but it does not seem to have any (visible) effect.
Is there any reason to have the hub disabled on edit?


The current edit where the hub is disabled
![image](https://user-images.githubusercontent.com/84850107/196892389-b1158037-91d6-439a-a12b-2bc1f76f1b2d.png)

Edit with the hub enabled
![image](https://user-images.githubusercontent.com/84850107/196891754-b6aaeb7e-cf7c-45de-90c5-3f1a385a5bec.png)

**Comment by chrieinv** [comment]
To answer my own question, if there are any reason not to have the hub enabled in edit, when opening the hub, the navigation bar at the top contains two options, 'Create Content' and 'Upload'. The option 'Create Content' would be confusing as you are changing content type, not creating new content.

**Comment by tmkarlsen** [comment]
Fixed.
