### ISSUE TITLE
Slow first load of Edlib/resources at the beginning of the day

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#987]
**Slow first load?**
Various users report that loading Edlib or resources for editing sometimes are very slow - the first time around. Next try is normal.

It seems to be related to the early attempts in the beginning of the day.

![Image](https://user-images.githubusercontent.com/38659798/168974755-82b67af3-ddfd-4d20-b714-63f9e65953e2.png)

![Image](https://user-images.githubusercontent.com/38659798/168974770-3cbb4b23-1c99-4842-bcfa-c03e7ae59900.png)

**Comment by tmkarlsen** [comment]
Estimated 26 hours

**Comment by tmkarlsen** [comment]
- Look into the CPU credit balance on AWS. Reports on this every morning.
- Check when backups run/finish

**Comment by emmachughes** [comment]
It's suspected that this happens due to a barrage of concurrent requests to CA from the so-called www service. We've noticed messages like these in the morning:

~~~
[13-May-2022 08:55:29] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
~~~

The successful responses are cached throughout the rest of the day. When all requests are successful, so-called www will begin loading again, giving the impression that this is caused by degraded server performance in the morning.

**Comment by emmachughes** [comment]
This is no longer applicable.
